# Pattern 1: Zone Resource Definition
# Registers zone with Global Control Plane

apiVersion: kuma.io/v1alpha1
kind: Zone
metadata:
  name: us-east
  labels:
    kuma.io/zone: us-east
spec:
  # Zone Ingress address for cross-zone communication
  ingress:
    address: 10.0.1.100:10001
  # Zone CP connection details
  controlPlane:
    address: grpcs://kuma-zone-control-plane.kuma-system:5676

