# Simple Single-Zone Mesh Setup Example
# Basic mesh configuration for local testing

apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: default
spec:
  mtls:
    backends:
    - name: builtin
      type: builtin
    enabledBackend: builtin
---
# Permissive traffic permission (allows all traffic)
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  name: allow-all
spec:
  targetRef:
    kind: Mesh
  from:
  - targetRef:
      kind: Mesh
---
# Example service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
  labels:
    kuma.io/service: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        kuma.io/service: frontend
      annotations:
        kuma.io/sidecar-injection: enabled
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 8080

